# Generated by Django 5.0 on 2023-12-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=8, verbose_name='Telephone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('telephone', models.CharField(max_length=8, verbose_name='Telephone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('statut_matrimonial', models.CharField(max_length=255, verbose_name='Statut matrimonial')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Specialite')),
            ],
        ),
        migrations.CreateModel(
            name='AgentComptable',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hopital.personnel')),
            ],
            bases=('hopital.personnel',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('personnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hopital.personnel')),
                ('age', models.PositiveIntegerField(blank=True, default=0, verbose_name='age')),
                ('grade', models.CharField(max_length=255, verbose_name='grade')),
            ],
            bases=('hopital.personnel',),
        ),
        migrations.CreateModel(
            name='PlanifierConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True, verbose_name='Date consultation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='consultations_planifier', to='hopital.patient', verbose_name='Patient')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_a_faire', to='hopital.medecin', verbose_name='Medecin consultant')),
                ('planificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planifications', to='hopital.medecin', verbose_name='Planificateur')),
            ],
        ),
        migrations.CreateModel(
            name='PrendreRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField(auto_now_add=True, verbose_name='Date du rendez vous')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='rdv', to='hopital.patient', verbose_name='Patient')),
                ('planificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs', to='hopital.agentcomptable', verbose_name='Planificateur')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_a_faire', to='hopital.medecin', verbose_name='Medecin consultant')),
            ],
        ),
        migrations.AddField(
            model_name='agentcomptable',
            name='patient',
            field=models.ManyToManyField(related_name='agents_comptable', through='hopital.PrendreRdv', to='hopital.patient'),
        ),
        migrations.AddField(
            model_name='agentcomptable',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_comptable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medecin',
            name='patient',
            field=models.ManyToManyField(related_name='medecins', through='hopital.PlanifierConsultation', to='hopital.patient'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialites',
            field=models.ManyToManyField(related_name='medecins', to='hopital.specialite'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_consultation', models.CharField(blank=True, max_length=255, verbose_name='Motif consultation')),
                ('date_diagnostic', models.DateField(auto_now_add=True, verbose_name='Date diagnostic')),
                ('anomalie_remarquee', models.TextField(verbose_name='Anomalie remarquée')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='hopital.patient', verbose_name='Patient')),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic', to='hopital.planifierconsultation', verbose_name='Consultation')),
                ('rdv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic', to='hopital.prendrerdv', verbose_name='Rdv')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='hopital.medecin', verbose_name='Medecin')),
            ],
        ),
    ]
