# Generated by Django 5.0 on 2023-12-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('diagnostic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyse', to='hopital.diagnostic', verbose_name='Daignostic')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='hopital.medecin', verbose_name='Medecin responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_prescrit', models.TextField(verbose_name='Medicament prescrit')),
                ('date_debut', models.DateField(auto_now_add=True, null=True, verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('diagnostic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='hopital.diagnostic', verbose_name='Daignostic')),
            ],
        ),
    ]
