# Generated by Django 5.0 on 2023-12-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_analyse_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='diagnostic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyse', to='hopital.diagnostic', verbose_name='Diagnostic'),
        ),
    ]
