# Generated by Django 5.0 on 2023-12-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_alter_analyse_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic', to='hopital.planifierconsultation', verbose_name='^planifier consultation'),
        ),
    ]
