# Generated by Django 5.0 on 2023-12-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_alter_diagnostic_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='consultation',
            new_name='planifier_consultation',
        ),
    ]
